### ISSUE TITLE
Is it possible to get an online version of the documentation?

### ISSUE THREAD

**Issue by imthenachoman** [lynxlynx/access#1]
I am interested in learning how it works and how to use it.

**Comment by lynxlynx** [comment]
Hi!
The documentation is already here inside manual pages, access.8 and access.conf.5. If you cannot read it, then I can draw it onto my site and provide direct links. Otherwise, this documentation should be full and comprehensive, along with (short) description of purpose in README.

**Comment by imthenachoman** [comment]
I was reading those there was a bunch of extra stuff like `.Dd`, `.Sh`, etc... I could not figure out how to compile those into something I can read more easily. I will keep looking. Thanks!

**Comment by lynxlynx** [comment]
These files are in mandoc/Unix manual page format. You should read them with a manual page reader this way: `man ./access.8`. If you really cannot read the files because you do not have manual page reader installed, then you can read https://lynxlynx.ru/access.8.html and https://lynxlynx.ru/access.conf.5.html versions online. HTH. Rys.

**Comment by imthenachoman** [comment]
Thank you so much! This is very helpful.

**Comment by lynxlynx** [comment]
In past there were text versions of these manual pages too. I thought it was very wasteful since everywhere I used access, there was a manual page viewer installed, either classic one or Linux one. If it is desirable, I can revert back the text versions alongside with manual page sources. What do you think?

**Comment by imthenachoman** [comment]
No need. I think the man pages are fine and the web versions you created do the job when needed. Thanks!

**Comment by lynxlynx** [comment]
Good then, I'm happy you're satisfied. I will soon make a nice website place dedicated to it. Closing.
